# Generated by Django 3.0.3 on 2020-02-27 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0004_empresa'),
        ('agencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.Empresa'),
        ),
    ]
