export const SHOW_FORM_ALICUOTA = "SHOW_FORM_ALICUOTA";

export const GET_ALICUOTAS = "GET_ALICUOTAS";
export const DELETE_ALICUOTA = "DELETE_ALICUOTA";
export const ADD_ALICUOTA = "ADD_ALICUOTA";
export const UPDATE_ALICUOTA = "UPDATE_ALICUOTA";

export const SET_ALICUOTA = "SET_ALICUOTA";
