export const SHOW_FORM_COBRADOR = "SHOW_FORM_COBRADOR";

export const GET_COBRADORES = "GET_COBRADORES";
export const DELETE_COBRADOR = "DELETE_COBRADOR";
export const ADD_COBRADOR = "ADD_COBRADOR";
export const UPDATE_COBRADOR = "UPDATE_COBRADOR";

export const SET_COBRADOR = "SET_COBRADOR";

export const TOGGLE_ESTADO_COBRADOR = "TOGGLE_ESTADO_COBRADOR";
