export const SHOW_FORM_CONDICION = "SHOW_FORM_CONDICION";

export const GET_CONDICIONES = "GET_CONDICIONES";
export const DELETE_CONDICION = "DELETE_CONDICION";
export const ADD_CONDICION = "ADD_CONDICION";
export const UPDATE_CONDICION = "UPDATE_CONDICION";

export const SET_CONDICION = "SET_CONDICION";
