export const SHOW_FORM_NOTIFICACION = "SHOW_FORM_NOTIFICACION";

export const GET_NOTIFICACIONES_RECIBIDAS = "GET_NOTIFICACIONES_RECIBIDAS";
export const GET_NOTIFICACIONES_ENVIADAS = "GET_NOTIFICACIONES_ENVIADAS";
export const DELETE_NOTIFICACION = "DELETE_NOTIFICACION";
export const ADD_NOTIFICACION = "ADD_NOTIFICACION";
export const UPDATE_NOTIFICACION = "UPDATE_NOTIFICACION";

export const SET_NOTIFICACION = "SET_NOTIFICACION";
export const TOGGLE_NOTIFICACION_LEIDA = "TOGGLE_NOTIFICACION_LEIDA";
