export const SHOW_FORM_PROVINCIA = "SHOW_FORM_PROVINCIA";

export const GET_PROVINCIAS = "GET_PROVINCIAS";
export const DELETE_PROVINCIA = "DELETE_PROVINCIA";
export const ADD_PROVINCIA = "ADD_PROVINCIA";
export const UPDATE_PROVINCIA = "UPDATE_PROVINCIA";

export const SET_PROVINCIA = "SET_PROVINCIA";
