# Generated by Django 3.0.3 on 2020-02-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alicuota_iva',
            name='codigo_Afip',
            field=models.CharField(max_length=4),
        ),
    ]
