# Generated by Django 3.0.3 on 2020-02-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_auto_20200224_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigo_postal',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='codigo_postal',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='codigo_postal',
            name='fm',
        ),
        migrations.RemoveField(
            model_name='codigo_postal',
            name='uc',
        ),
        migrations.RemoveField(
            model_name='codigo_postal',
            name='um',
        ),
    ]
