# Generated by Django 3.0.3 on 2020-02-27 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bases', '0003_auto_20200224_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('domicilio', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('cuit', models.CharField(max_length=150)),
                ('inicio_actividades', models.DateField(blank=True, null=True)),
                ('iibb', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logo_pics')),
                ('codigo_postal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.Codigo_Postal')),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.Condicion_IVA')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
