# Generated by Django 3.0.3 on 2020-03-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0004_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_documento',
            options={'verbose_name_plural': 'Tipos de Documentos'},
        ),
    ]
