# Generated by Django 3.0.3 on 2020-03-12 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencias', '0003_cobrador_tarifa_zona'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bases', '0005_auto_20200312_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('nro_documento', models.CharField(blank=True, max_length=11, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('representante', models.CharField(blank=True, max_length=150, null=True)),
                ('agencias', models.ManyToManyField(to='agencias.Agencia')),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencias.Cobrador')),
                ('codigo_postal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.Codigo_Postal')),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.Condicion_IVA')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencias.Tarifa')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.Tipo_Documento')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencias.Zona')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
