# Generated by Django 3.0.3 on 2020-03-15 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agencias', '0003_cobrador_tarifa_zona'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='agencias',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cobrador',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tarifa',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='zona',
        ),
        migrations.CreateModel(
            name='Clientes_Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencias.Agencia')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencias.Cobrador')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencias.Tarifa')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencias.Zona')),
            ],
            options={
                'verbose_name_plural': 'Clientes por Agencia',
                'unique_together': {('agencia', 'cliente')},
            },
        ),
    ]
