# Generated by Django 3.0.3 on 2020-03-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200315_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nro_documento',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
